// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewRoom struct {
	PlayerName string `json:"playerName"`
}

type Player struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Response struct {
	Player *Player `json:"player"`
	Room   *Room   `json:"room"`
}

type Room struct {
	ID      string    `json:"id"`
	Host    *Player   `json:"host"`
	Members []*Player `json:"members"`
}
